import type { ADRStatus } from "@/lib/adrs";

export type ADRCase002Domain = "founding" | "data" | "content" | "philosophy" | "architecture";

export interface ADRCase002 {
  id: string;
  number: string;
  title: string;
  status: ADRStatus;
  freshness: "Active" | "Permanent" | "Pending";
  freshnessNote: string;
  date: string;
  domain: ADRCase002Domain;
  position: "Foundational" | "Derived" | "Permanent" | "Pending";
  dependsOn: string[];
  summary: string;
  tags: string[];
}

// C2-001 through C2-012: AI extrapolated from operator seeds.
// Preserved as scars — the record of what AI fabricated.
// See /interview for the audit that produced the corrected ADRs (C2-013 onward).
export const adrsCase002: ADRCase002[] = [
  {
    id: "C2-001",
    number: "001",
    title: "Domain & Identity — yysworld.com",
    status: "AI Extrapolated",
    freshness: "Permanent",
    freshnessNote: "Preserved as scar. Corrected reasoning in C2-013.",
    date: "2026-03-30",
    domain: "founding",
    position: "Foundational",
    dependsOn: [],
    summary: "AI extrapolated WHY from content-strategy logic. Real WHY: domain bought decades ago, incubating. No alternatives considered. See C2-013 for operator-supplied founding origin.",
    tags: ["ai-extrapolated", "scar", "domain", "founding"],
  },
  {
    id: "C2-002",
    number: "002",
    title: "Primary Audience — Kids, Not Parents",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Corrected reasoning in C2-014.",
    date: "2026-03-30",
    domain: "founding",
    position: "Derived",
    dependsOn: ["C2-001"],
    summary: "AI invented age range 8–14 and 'formation stage' framing. Real model: Calvin and Hobbes — speaks to kids, anyone who thinks like one is welcome. See C2-014.",
    tags: ["ai-extrapolated", "scar", "audience"],
  },
  {
    id: "C2-003",
    number: "003",
    title: "Data Posture — Outward-Only",
    status: "AI Extrapolated",
    freshness: "Permanent",
    freshnessNote: "Preserved as scar. WHY was platform-critique framing AI imposed. Real WHY: one of 6 constraints enabling creative freedom + AI legibility.",
    date: "2026-03-30",
    domain: "data",
    position: "Foundational",
    dependsOn: [],
    summary: "Operator-supplied posture holds. AI imposed platform-critique framing that was not operator's. Real WHY: structural choice maximizing creative freedom, not a reaction to other platforms.",
    tags: ["ai-extrapolated", "scar", "data-posture"],
  },
  {
    id: "C2-004",
    number: "004",
    title: "COPPA Compliance Architecture",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Corrected reasoning in C2-018.",
    date: "2026-03-30",
    domain: "data",
    position: "Derived",
    dependsOn: ["C2-003"],
    summary: "AI invented compliance architecture framing from first principles. Real WHY: operator has prior experience with a kids virtual world and designed to eliminate COPPA's jurisdiction entirely. See C2-018.",
    tags: ["ai-extrapolated", "scar", "coppa"],
  },
  {
    id: "C2-005",
    number: "005",
    title: "Entry Schema — The Six Fields",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Schema was entirely fabricated. Real 6 are the YY Method compliance criteria. See C2-016.",
    date: "2026-03-30",
    domain: "content",
    position: "Foundational",
    dependsOn: [],
    summary: "AI invented DECISION·WHY·WHY-NOT·BREAKS IF·EXPIRES·YY'S TAKE schema. The real 6 are the YY Method compliance criteria: Compression·Scars·Survivability·Explainability·Timestamping·Discipline. See C2-016.",
    tags: ["ai-extrapolated", "scar", "schema"],
  },
  {
    id: "C2-006",
    number: "006",
    title: "YY's Role — Protagonist, Co-Author, Authentication",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Three-role framing was AI-constructed. Fabricated acorn preference and metronome incident. See C2-015.",
    date: "2026-03-30",
    domain: "content",
    position: "Derived",
    dependsOn: ["C2-001", "C2-005"],
    summary: "AI fabricated acorn preference, metronome incident, and three-role framework. YY's real character: impatient, direct, 'Booooooring!!', full range of emotion, liberated in yysworld.com. See C2-015.",
    tags: ["ai-extrapolated", "scar", "yy", "fabricated-incidents"],
  },
  {
    id: "C2-007",
    number: "007",
    title: "Anti-Smoothing Principle — Provenance, Not Style",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. 'Anti-smoothing' is AI's language. Operator's language is cognitive theft. This ADR dissolves into C2-017.",
    date: "2026-03-30",
    domain: "content",
    position: "Derived",
    dependsOn: ["C2-006"],
    summary: "'Anti-smoothing' is AI's surface description of a symptom. Operator's language is cognitive theft — the actual crime, subtle and more dangerous. This ADR is superseded by C2-017.",
    tags: ["ai-extrapolated", "scar", "wrong-language"],
  },
  {
    id: "C2-008",
    number: "008",
    title: "Stealth Inoculation — The Lesson Is Never Named",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Operator supplied inoculation language. AI stripped the tsunami stakes. See C2-017.",
    date: "2026-03-30",
    domain: "content",
    position: "Derived",
    dependsOn: ["C2-002", "C2-007"],
    summary: "Operator supplied 'inoculation against cognitive theft.' AI kept the word but dropped the stakes: AI becomes a tsunami in kids' lifetimes. The urgency was the point. See C2-017.",
    tags: ["ai-extrapolated", "scar", "stakes-stripped"],
  },
  {
    id: "C2-009",
    number: "009",
    title: "Cognitive Theft as Archnemesis",
    status: "AI Extrapolated",
    freshness: "Permanent",
    freshnessNote: "Preserved as scar. Operator-supplied framing holds but AI invented the taxonomy distinguishing it from lying/misinformation. See C2-017.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-007", "C2-008"],
    summary: "Operator supplied 'cognitive theft is YY's archnemesis' and 'provenance is YY DNA.' AI invented taxonomy separating it from lying/misinformation. Operator's framing: it is subtle, dangerous, happens to best and brightest first. See C2-017.",
    tags: ["ai-extrapolated", "scar", "invented-taxonomy"],
  },
  {
    id: "C2-010",
    number: "010",
    title: "The Acorn Economy — Untraceable Return",
    status: "AI Extrapolated",
    freshness: "Active",
    freshnessNote: "Preserved as scar. Acorn economy was entirely AI-invented. Operator thinks in dandelion seeds. See C2-019.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-003"],
    summary: "Acorn economy was AI construction from YY's squirrel character. Operator's actual metaphor: dandelion seeds. Ben is the plant. Seeds blow freely. Take root when hardy. Become plants themselves. See C2-019.",
    tags: ["ai-extrapolated", "scar", "wrong-metaphor"],
  },
  {
    id: "C2-011",
    number: "011",
    title: "Employer Inversion — Same Method, Opposite Direction",
    status: "AI Extrapolated",
    freshness: "Permanent",
    freshnessNote: "Preserved as scar. Inversion concept holds but WHY was wrong. AI framed employer as adversary. See C2-021.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-003", "C2-010"],
    summary: "AI framed employer as adversary and the inversion as protection from institutional absorption. Real WHY: employer is liberation — enables the creative work. yysworld.com is made possible by that security. See C2-021.",
    tags: ["ai-extrapolated", "scar", "employer-framing-wrong"],
  },
  {
    id: "C2-012",
    number: "012",
    title: "Technical Stack — Static-First, Zero Extraction Surface",
    status: "AI Extrapolated",
    freshness: "Pending",
    freshnessNote: "Preserved as scar. Stack decision not yet made by operator. AI recommendation noted and found useful. See C2-023.",
    date: "2026-03-30",
    domain: "architecture",
    position: "Pending",
    dependsOn: ["C2-004"],
    summary: "AI assumed same stack as home.yymethod.com without operator confirmation. Stack is pending operator decision. AI recommendation (Next.js static export, Vercel) found useful — may be followed. See C2-023.",
    tags: ["ai-extrapolated", "scar", "pending-decision"],
  },

  // C2-013 onward: operator-supplied reasoning from the Interview with AI session.
  // Date: March 30, 2026. See /interview for the full source record.

  {
    id: "C2-013",
    number: "013",
    title: "Founding Origin — Decades Incubating, Right Timing",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent founding record.",
    date: "2026-03-30",
    domain: "founding",
    position: "Foundational",
    dependsOn: [],
    summary: "Domain bought decades ago, incubating. No alternatives considered — this was always the domain. Current life secured, kids more grown up. Motivation: fun, exercising AI muscles, exploring the vast ocean of possibilities. The 6 constraints paradoxically maximize creative freedom while keeping artifacts legible to AI.",
    tags: ["founding", "origin", "timing", "motivation", "operator-supplied"],
  },
  {
    id: "C2-014",
    number: "014",
    title: "Calvin and Hobbes Audience Model",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Expires if site pivots away from direct kid-voice.",
    date: "2026-03-30",
    domain: "founding",
    position: "Derived",
    dependsOn: ["C2-013"],
    summary: "Primary voice speaks to kids directly. Anyone who thinks like a kid is welcome — no age gate. Model: Calvin and Hobbes. Ostensibly for kids, actually for anyone. The strip never explains itself. Kids read it at their level; adults at theirs. The voice is kid-facing but the invitation is open.",
    tags: ["audience", "calvin-hobbes", "open-invitation", "no-age-gate", "operator-supplied"],
  },
  {
    id: "C2-015",
    number: "015",
    title: "YY Liberated — Full Range, Unfettered",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Expires if YY's voice is edited for palatability.",
    date: "2026-03-30",
    domain: "content",
    position: "Foundational",
    dependsOn: ["C2-013"],
    summary: "YY plays the same role as in yyand.me — but unfettered. Full range of human emotion. Not Ben's sidekick; his own being. YY vocalized what Ben felt internally — the unfiltered voice that couldn't be polished. Already proven on Ben's kids, who built uninhibited YY spinoffs they own outright. Liberating YY is continuing what he already is.",
    tags: ["yy", "liberated", "full-range", "proven-on-kids", "operator-supplied"],
  },
  {
    id: "C2-016",
    number: "016",
    title: "Six Invariants as DNA — Freely Lensed",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The invariants are DNA — they do not change. The surface form they take is always open.",
    date: "2026-03-30",
    domain: "content",
    position: "Foundational",
    dependsOn: [],
    summary: "Every yysworld.com artifact satisfies all 6 YY Method compliance criteria: Compression · Scars · Survivability · Explainability · Timestamping · Discipline. These are the DNA — hand and palm from the early version of the method. Not a template. Operator lenses them freely into any surface form. An artifact is valid when all 6 can be traced through it, whatever shape it takes.",
    tags: ["six-invariants", "dna", "compliance-criteria", "freely-lensed", "operator-supplied"],
  },
  {
    id: "C2-017",
    number: "017",
    title: "Cognitive Theft — The Tsunami",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The threat grows; the defense must be planted early.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Foundational",
    dependsOn: [],
    summary: "Cognitive theft is YY's archnemesis. Subtle, dangerous, happens to the best and brightest fastest because they use AI most. Inoculation against it is urgent: AI becomes a tsunami in kids' lifetimes. Origin: the Fourth Scar — 5 months, 200+ hours, 6 podcast episodes, 5 essays, all smoothed by AI. Operator experienced it, named it, documented it. yysworld.com plants the antibody before patterns calcify.",
    tags: ["cognitive-theft", "tsunami", "fourth-scar", "inoculation", "archnemesis", "operator-supplied"],
  },
  {
    id: "C2-018",
    number: "018",
    title: "COPPA by Elimination — No Jurisdiction to Grab",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Expires if any data collection is introduced.",
    date: "2026-03-30",
    domain: "data",
    position: "Derived",
    dependsOn: ["C2-013"],
    summary: "Operator has prior direct experience with a kids virtual world — learned COPPA from the inside. Designed yysworld.com to have nothing COPPA can grab: no data collected, no consent surface, no liability target. This is not compliance architecture. It is elimination of the regulatory surface entirely, maximizing creative freedom without a constant target on the back.",
    tags: ["coppa", "elimination", "prior-experience", "no-target", "operator-supplied"],
  },
  {
    id: "C2-019",
    number: "019",
    title: "Dandelion Seeds — Impact Without a Map",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Expires if a revenue motive attaches to impact.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-013"],
    summary: "Ben is the plant. Seeds blow freely — no tracking, no map, no accounting for where they land. The ones that take root become plants themselves and blow their own seeds. Proof: Ben's kids took YY and built their own uninhibited spinoffs. Seeds only take root when hardy enough for the environment. AI is a force multiplier only when soil and seed are both already strong.",
    tags: ["dandelion-seeds", "impact", "no-tracking", "generational", "operator-supplied"],
  },
  {
    id: "C2-020",
    number: "020",
    title: "AI as Force Multiplier — Condition: Strong Soil and Seed",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent condition.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-016", "C2-017"],
    summary: "AI participates as force multiplier only when soil and seed are both already strong. AI does not create strength — it multiplies what is there. Weak soil + AI = amplified weakness. Strong soil + strong seed + AI = exponential growth. The 6 invariants make the seed strong before AI touches it. Operator governs; AI co-produces within that governance.",
    tags: ["ai-force-multiplier", "condition", "governance", "soil-and-seed", "operator-supplied"],
  },
  {
    id: "C2-021",
    number: "021",
    title: "Employer as Liberation — The Enabler",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Expires if employment situation changes materially.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Derived",
    dependsOn: ["C2-013"],
    summary: "The employer is not the adversary — the employer is liberation. Current life secured. Family taken care of. Thriving at the highest level, a force multiplier for AI and for change. yysworld.com is what becomes possible in the margins of that security. Same DNA as the professional method, different direction. Both serve their purpose. Neither competes with the other.",
    tags: ["employer", "liberation", "enabler", "margins", "operator-supplied"],
  },
  {
    id: "C2-022",
    number: "022",
    title: "Genealogical Artifact — A Life Structured to Survive",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The genealogical purpose does not expire.",
    date: "2026-03-30",
    domain: "philosophy",
    position: "Foundational",
    dependsOn: ["C2-016"],
    summary: "yysworld.com is simultaneously a site for kids and a genealogical artifact of Ben's life. The 6 invariants — especially Scars and Timestamping — make every entry a life record. YY has been with Ben for 40 years; entries with YY document both of them. The surface form is open. The genealogical purpose is permanent. Precursor: 300 YouTube videos, 16 million views — practice logs in public, scars visible.",
    tags: ["genealogical-artifact", "life-record", "scars-visible", "yy-40-years", "operator-supplied"],
  },
  {
    id: "C2-023",
    number: "023",
    title: "Technical Stack — Pending Operator Decision",
    status: "Pending",
    freshness: "Pending",
    freshnessNote: "Pending. Expires when operator decides.",
    date: "2026-03-30",
    domain: "architecture",
    position: "Pending",
    dependsOn: ["C2-018"],
    summary: "Stack not yet decided as of March 30, 2026. AI recommendation: Next.js static export on Vercel — same tooling as home.yymethod.com, zero runtime extraction surface, familiar, proven. Operator found this useful and may follow it. This is AI multiplying well: strong existing stack, clear constraints from outward-only posture, AI proposed, operator evaluates.",
    tags: ["stack", "pending", "ai-recommendation", "next-js-static", "operator-evaluating"],
  },
];

export function getADRCase002(id: string): ADRCase002 | undefined {
  return adrsCase002.find((a) => a.id === id);
}

export function getADRsCase002ByDomain(domain: ADRCase002Domain): ADRCase002[] {
  return adrsCase002.filter((a) => a.domain === domain);
}

export const domainLabelCase002: Record<ADRCase002Domain, string> = {
  founding: "Founding",
  data: "Data & COPPA",
  content: "Content",
  philosophy: "Philosophy",
  architecture: "Architecture",
};
