import type { ADRStatus } from "@/lib/adrs";

export type ADRCase004Domain = "principle" | "architecture" | "operations" | "governance";

export interface ADRCase004 {
  id: string;
  number: string;
  title: string;
  status: ADRStatus;
  freshness: "Active" | "Permanent" | "Pending";
  freshnessNote: string;
  date: string;
  domain: ADRCase004Domain;
  position: "Foundational" | "Derived";
  dependsOn: string[];
  summary: string;
  tags: string[];
}

export const adrsCase004: ADRCase004[] = [
  {
    id: "C4-001",
    number: "001",
    title: "Keep Sensitive Compute Local — Remote the Operator, Not the Data",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Becomes stale if confidentiality requirements, endpoint trust model, or approved AI usage model change.",
    date: "2026-04-05",
    domain: "principle",
    position: "Foundational",
    dependsOn: [],
    summary: "Local-first is the governing principle, not an optimization. Remote access moves the operator to the work — never the work into a new trust domain. Sensitive computation stays on controlled work endpoints. Remote devices are control surfaces only. Scar: early framing centered on convenience. Trust-boundary primacy arrived late and should have been the first question.",
    tags: ["local-first", "trust-boundary", "sensitive-compute", "cloud-ai", "custody", "foundational"],
  },
  {
    id: "C4-002",
    number: "002",
    title: "Separate Control Surfaces from Execution Surfaces",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if portable devices begin hosting durable work context or if the execution environment becomes distributed by design.",
    date: "2026-04-05",
    domain: "principle",
    position: "Derived",
    dependsOn: ["C4-001"],
    summary: "Control surfaces and execution surfaces are distinct by design. Personal devices control; work-managed endpoints execute. Mobile and portable devices remain lightweight and unencumbered by sensitive execution state. Role separation reduces leakage, ambiguity, and attack surface. Each device class does what it is best at — without being asked to do what it is not.",
    tags: ["control-surface", "execution-surface", "role-separation", "device-boundary", "separation"],
  },
  {
    id: "C4-003",
    number: "003",
    title: "Use a Private Overlay Network — Not Publicly Exposed Remote Services",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Becomes stale if the private overlay can no longer meet performance, policy, or assurance needs.",
    date: "2026-04-05",
    domain: "principle",
    position: "Derived",
    dependsOn: ["C4-001", "C4-002"],
    summary: "Public exposure of management services is rejected. All remote access traverses a private overlay or equivalent zero-trust channel. The execution surface remains dark to the public internet while staying reachable from approved endpoints. Reduces brute-force exposure, port management complexity, and unsafe compensating controls.",
    tags: ["private-overlay", "zero-trust", "remote-access", "network-security", "public-exposure"],
  },
  {
    id: "C4-004",
    number: "004",
    title: "Preserve the Method — Do Not Publish the Client's Concrete Deployment",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify before any broader publication or derivative teaching use.",
    date: "2026-04-05",
    domain: "principle",
    position: "Derived",
    dependsOn: ["C4-001"],
    summary: "The case study preserves reasoning, constraints, tradeoffs, and scars. Client-identifying topology, commands, addresses, and defensive posture are abstracted or omitted. The method is teachable without disclosing the instance. Specificity degrades client security; omission loses methodological force. The balance is principled abstraction.",
    tags: ["publication", "obfuscation", "client-protection", "method-vs-deployment", "abstraction"],
  },
  {
    id: "C4-005",
    number: "005",
    title: "Assign Distinct Roles to Distinct Machines — No Unified Pattern",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if one machine class disappears, becomes managed differently, or takes on materially new responsibilities.",
    date: "2026-04-05",
    domain: "architecture",
    position: "Derived",
    dependsOn: ["C4-001", "C4-002", "C4-003", "C4-004"],
    summary: "The environment has distinct endpoint classes: office-bound automation node, portable secure work node, and personal control surfaces. Each retains its own role, power policy, and interaction pattern. Forcing one machine pattern onto all creates wrong defaults on at least one class. Role specialization is not overhead — it is the architecture.",
    tags: ["machine-roles", "role-architecture", "device-specialization", "endpoint-classes"],
  },
  {
    id: "C4-006",
    number: "006",
    title: "Maintain a Portable Secure Work Node as the Primary Remote Execution Surface",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the portable endpoint stops being the practical remote anchor or if policy changes remove its suitability.",
    date: "2026-04-05",
    domain: "architecture",
    position: "Derived",
    dependsOn: ["C4-005"],
    summary: "One portable endpoint serves as the primary remote execution surface. Reachable from variable networks, supports heavier local workloads when required, and maintains continuity between office and travel contexts without moving sensitive work onto personal devices or cloud services. This is the endpoint the window opens onto.",
    tags: ["portable-node", "remote-execution", "travel-continuity", "heavy-inference"],
  },
  {
    id: "C4-007",
    number: "007",
    title: "Keep the Office Automation Node Awake Only When Automation Is Active",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the automation becomes mission-critical outside office hours or if peripherals require a different sleep policy.",
    date: "2026-04-05",
    domain: "architecture",
    position: "Derived",
    dependsOn: ["C4-005", "C4-006"],
    summary: "The office-bound node supports ambient automation during office presence. Wakefulness is conditional: active during live automation windows, sleep allowed and preferred when automation ends or the machine is idle. 'Always awake' wastes power. 'Always sleep' breaks automation. Conditional wakefulness tied to active work is the correct policy.",
    tags: ["office-node", "automation", "sleep-policy", "conditional-wakefulness", "power"],
  },
  {
    id: "C4-008",
    number: "008",
    title: "Prefer Command-First Mobile Interaction — Reserve Full Remote Desktop for Escalation",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if phone-based work becomes primarily graphical or if command-first stops covering the majority of mobile needs.",
    date: "2026-04-05",
    domain: "architecture",
    position: "Derived",
    dependsOn: ["C4-005"],
    summary: "Mobile interaction defaults to secure command execution and status retrieval — not full graphical remoting. Phone-sized screens make visual remoting expensive for routine tasks: high bandwidth, latency-sensitive, poor ergonomics. Command-first is faster, more reliable on unstable networks, and suited to brief operational windows. Full remote desktop remains available as escalation.",
    tags: ["mobile", "command-first", "remote-desktop", "ergonomics", "fragmented-time"],
  },
  {
    id: "C4-009",
    number: "009",
    title: "Build a Command System with Progressive Promotion — Repeated Actions Earn Their Shortcut",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the command taxonomy becomes brittle or if mobile ergonomics change substantially.",
    date: "2026-04-05",
    domain: "architecture",
    position: "Derived",
    dependsOn: ["C4-005", "C4-008"],
    summary: "Three-layer interaction model: raw command access for full flexibility, reusable named commands for structured operations, shortcuts promoting only the most-repeated actions. Repeated actions become cheaper over time without surrendering the general case. Shortcut promotion is subordinate to the command layer — not a replacement for it. The future command set is emergent, not predetermined.",
    tags: ["command-system", "progressive-promotion", "shortcuts", "three-layer", "ergonomics"],
  },
  {
    id: "C4-010",
    number: "010",
    title: "Put Admission Control in Front of Heavy Local Inference",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the hardware envelope changes enough to justify broader concurrency.",
    date: "2026-04-05",
    domain: "operations",
    position: "Derived",
    dependsOn: ["C4-005", "C4-007"],
    summary: "Heavy local inference is not a casual process class. A small number of overlapping launches creates disproportionate thermal and performance cost. The portable work node requires a guarded admission layer: check current load, enforce conservative concurrency limits, refuse unsafe starts with clear reasons. Safe refusal is preferable to opportunistic overload.",
    tags: ["admission-control", "heavy-inference", "local-llm", "guardrails", "concurrency"],
  },
  {
    id: "C4-011",
    number: "011",
    title: "Pair Every Guardrail with Status, Kill, and Recovery Paths",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if job orchestration moves to a more formal supervisor or queueing system.",
    date: "2026-04-05",
    domain: "operations",
    position: "Derived",
    dependsOn: ["C4-010"],
    summary: "Blocking unsafe starts without paired observability creates a different kind of brittleness. Every heavy-work admission layer requires: a concise status command, a targeted kill path, a stale-state recovery path, and logs readable from mobile. Guardrails without recovery eventually produce unsafe bypasses. The operator needs fast emergency control from away.",
    tags: ["guardrails", "status", "kill-path", "recovery", "mobile-observability", "stale-state"],
  },
  {
    id: "C4-012",
    number: "012",
    title: "Set Power Policy by Machine Role — Not a Single Global Preference",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if device roles, thermal limits, or office patterns change materially.",
    date: "2026-04-05",
    domain: "operations",
    position: "Derived",
    dependsOn: ["C4-005", "C4-009", "C4-010"],
    summary: "Power policy is architectural. Different machine roles require contradictory power behavior: the office node sleeps when inactive, the portable node stays reachable but reduces idle draw, control devices are opportunistic and disposable. A single global rule — never sleep, or sleep aggressively — fails once machine roles diverge. Policy follows role.",
    tags: ["power-policy", "role-specific", "sleep", "availability", "idle-draw"],
  },
  {
    id: "C4-013",
    number: "013",
    title: "The Portable Work Node Must Support Both Remote and Local Use Without Reconfiguration Debt",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if one operating mode becomes negligible.",
    date: "2026-04-05",
    domain: "operations",
    position: "Derived",
    dependsOn: ["C4-005", "C4-010"],
    summary: "The portable work node is not purely headless. It may be opened and used directly at the office, then returned to remote-optimized operation later. Mode transitions carry minimal cost by design. A device that works only when closed or only when open creates operational drag. Dual-mode is the correct baseline.",
    tags: ["dual-mode", "portable-node", "local-use", "remote-use", "reconfiguration"],
  },
  {
    id: "C4-014",
    number: "014",
    title: "Treat Tablet-Class Devices as Auxiliary Surfaces — Not Trust-Boundary Shortcuts",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the tablet becomes essential rather than optional.",
    date: "2026-04-05",
    domain: "operations",
    position: "Derived",
    dependsOn: ["C4-003", "C4-012", "C4-013"],
    summary: "Tablet-class devices are optional — auxiliary display or control surfaces in travel contexts. Identity separation and device-role boundaries are preserved regardless of tablet presence. The trust model remains intact if the tablet is absent. Convenience at the tablet cannot justify collapsing separation that was intentionally preserved.",
    tags: ["tablet", "auxiliary-surface", "identity-separation", "secondary-display", "optional"],
  },
  {
    id: "C4-015",
    number: "015",
    title: "Preserve the Boundary Between Personal Method Ownership and Work-Context Application",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the legal or organizational framing of method versus engagement changes.",
    date: "2026-04-05",
    domain: "governance",
    position: "Derived",
    dependsOn: ["C4-001", "C4-004"],
    summary: "The personal method predates and outlives any professional engagement. Methodology — principles, reasoning patterns, decision structures — is captured at the principle level and remains the operator's. Work-context execution, refinements, and artifacts belong to the client environment. The distinction preserves both intellectual clarity and professional hygiene.",
    tags: ["method-ownership", "client-boundary", "ip-hygiene", "professional-method", "governance"],
  },
  {
    id: "C4-016",
    number: "016",
    title: "Publish the Reasoning Chain — Obfuscate the Deployment",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify before reuse in talks, training, or external publication.",
    date: "2026-04-05",
    domain: "governance",
    position: "Derived",
    dependsOn: [
      "C4-001", "C4-002", "C4-003", "C4-004", "C4-005",
      "C4-006", "C4-007", "C4-008", "C4-009", "C4-010",
      "C4-011", "C4-012", "C4-013", "C4-014", "C4-015",
    ],
    summary: "Publication preserves the full decision chain — principles, tradeoffs, constraints, reverify conditions, scars. It withholds device-specific names, addresses, commands, schedules, pathnames, and client-identifying markers. The method is valuable because it shows how judgment was structured under constraint. The deployment becomes dangerous when enough detail accumulates to map the client's environment.",
    tags: ["publication-standard", "obfuscation-rules", "reasoning-chain", "case-study", "governance"],
  },
];

export function getADRCase004(id: string): ADRCase004 | undefined {
  return adrsCase004.find((a) => a.id === id);
}

export function getADRsCase004ByDomain(domain: ADRCase004Domain): ADRCase004[] {
  return adrsCase004.filter((a) => a.domain === domain);
}

export const domainLabelCase004: Record<ADRCase004Domain, string> = {
  principle: "Foundational Principles",
  architecture: "System Architecture",
  operations: "Operations & Safeguards",
  governance: "Governance",
};
