export type ADRStatus = "Decided" | "Decided — Rejected" | "Decided — Correction" | "Decided — Partially Corrected" | "Pending" | "Permanent Record" | "AI Extrapolated";

export type ADRFreshness = "Active" | "Executed" | "Pending" | "Permanent";

export interface ADR {
  id: string;
  number: string;
  title: string;
  status: ADRStatus;
  freshness: ADRFreshness;
  freshnessNote: string;
  date: string;
  domain: "tax" | "identity" | "agent" | "device" | "methodology";
  position: "Foundational" | "Derived" | "Cross-cutting" | "Correction" | "Forward-looking" | "Permanent";
  dependsOn: string[];
  summary: string;
  tags: string[];
}

export const adrs: ADR[] = [
  {
    id: "ADR-001",
    number: "001",
    title: "S Corp Election Termination Timing",
    status: "Decided",
    freshness: "Executed",
    freshnessNote: "Expires if entity structure changes",
    date: "2026-03-29",
    domain: "tax",
    position: "Foundational",
    dependsOn: [],
    summary: "Terminate S corp election effective April 1, 2026. March 31 is the final day. Clean quarter-end timing. 5-year re-election lockout through 2030.",
    tags: ["s-corp", "entity", "timing", "foundational"],
  },
  {
    id: "ADR-002",
    number: "002",
    title: "Final Payroll Bonus Strategy",
    status: "Decided — Partially Corrected",
    freshness: "Executed",
    freshnessNote: "Expires March 31, 2026 upon execution. FICA assumption corrected by ADR-025.",
    date: "2026-03-29",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-001", "ADR-007"],
    summary: "Run final S corp payroll with ~$20k bonus. Total W-2 ~$60k. Fund employer 401(k) simultaneously. FICA assumption (Medicare-only) was incorrect — corrected by ADR-025. Full FICA applies.",
    tags: ["payroll", "bonus", "401k", "deadline"],
  },
  {
    id: "ADR-003",
    number: "003",
    title: "Employee Deferral vs Employer Contribution Priority",
    status: "Decided",
    freshness: "Executed",
    freshnessNote: "Expires if 2026 annual deferral limit changes",
    date: "2026-03-29",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-001", "ADR-002"],
    summary: "Skip employee deferral from S corp bonus. Preserve capital for employer contribution. Employee deferral flows through employer W-2 payroll April–December. Irreplaceable/fungible distinction.",
    tags: ["401k", "deferral", "employer-contribution", "priority"],
  },
  {
    id: "ADR-004",
    number: "004",
    title: "Distribution Reclassification — Considered and Rejected",
    status: "Decided — Rejected",
    freshness: "Permanent",
    freshnessNote: "Permanent record. Window closed March 31.",
    date: "2026-03-29",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-002", "ADR-003"],
    summary: "Q1 distributions (~$30k) left as characterized. Reclassification rejected due to execution risk under 48-hour deadline. Cost of decision: ~$7,500 forgone. Deliberate risk-adjusted choice.",
    tags: ["distributions", "reclassification", "rejected", "risk"],
  },
  {
    id: "ADR-005",
    number: "005",
    title: "Retirement Vehicle Transition — S Corp to LLC",
    status: "Decided — Partially Corrected",
    freshness: "Pending",
    freshnessNote: "Expires if employer plan rollover rules confirmed otherwise. Two claims corrected by ADR-023.",
    date: "2026-03-29",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-001", "ADR-003"],
    summary: "Transition from S corp retirement structure to LLC/employer plan structure. ⚠ Partially corrected by ADR-023: solo 401(k) is NOT frozen after April 1 — LLC (disregarded entity) can sponsor it with SE income as contribution basis. SEP-IRA is generally inferior to solo 401(k) at the same income level. IRA rollover window also remained open.",
    tags: ["solo-401k", "sep-ira", "rollover", "retirement", "partially-corrected"],
  },
  {
    id: "ADR-006",
    number: "006",
    title: "Cash & Banking Execution — Conditional Wire Strategy",
    status: "Decided",
    freshness: "Executed",
    freshnessNote: "Expires March 31, 2026 — execution complete",
    date: "2026-03-29",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-002", "ADR-003"],
    summary: "Deploy full ~$30k. No cash reserve held — April 1 entity becomes disregarded, cash moves freely. Credit card float covers expenses. Wire if needed for same-day funding.",
    tags: ["banking", "wire", "cash", "conditional"],
  },
  {
    id: "ADR-007",
    number: "007",
    title: "Tax Bracket Reality — Federal + State Combined Rate",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Expires if filing status, state rate, or income composition changes",
    date: "2026-03-29",
    domain: "tax",
    position: "Cross-cutting",
    dependsOn: [],
    summary: "29% combined marginal rate: 24% federal (MFJ) + 5% state (illustrative). Real 2026 MFJ brackets applied. Every dollar sheltered in traditional 401(k) saves $0.29.",
    tags: ["bracket", "marginal-rate", "state-rate", "cross-cutting"],
  },
  {
    id: "ADR-008",
    number: "008",
    title: "Employer Contribution Basis Correction",
    status: "Decided — Correction",
    freshness: "Permanent",
    freshnessNote: "Permanent — supersedes bonus figures in ADR-002, ADR-006",
    date: "2026-03-29",
    domain: "tax",
    position: "Correction",
    dependsOn: [],
    summary: "Employer contribution = 25% of bonus amount only, not total W-2. Corrects prior calculation error. ~$20,000 employer contribution from available cash.",
    tags: ["employer-contribution", "correction", "basis"],
  },
  {
    id: "ADR-009",
    number: "009",
    title: "DAF Charitable Front-Load Strategy — Two Phase",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires if charitable contribution amount, bracket trajectory, or DAF rules change",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-007", "ADR-004"],
    summary: "Phase 1: front-load at current 29% combined rate with appreciated securities. Phase 2: repeat when bracket increases. Two-phase charitable obligation executed as bracket-progression arbitrage. ~$13k total savings vs annual cash giving.",
    tags: ["daf", "charitable", "appreciated-securities", "two-phase"],
  },
  {
    id: "ADR-010",
    number: "010",
    title: "FSA Election — Max Contribution Strategy",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires when enrollment window closes. Re-evaluate annually.",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-007"],
    summary: "Elect max FSA contribution through employer. FICA efficiency at current income level. Use-it-or-lose-it managed via dependent care or medical spend plan.",
    tags: ["fsa", "enrollment", "fica"],
  },
  {
    id: "ADR-011",
    number: "011",
    title: "Paychex Flex Deferral Setup & DCA Strategy",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires when annual cap hit (~Oct 2026). Update every September.",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-003", "ADR-007"],
    summary: "Set up employee deferral through Paychex Flex at employer. DCA approach: spread over April–October rather than front-loading, to preserve flexibility for year-end adjustments.",
    tags: ["paychex", "dca", "deferral", "401k"],
  },
  {
    id: "ADR-012",
    number: "012",
    title: "Minor Child Employment — LLC Disregarded Entity",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires if child turns 18, work type changes, or state WC rules change",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-001", "ADR-007"],
    summary: "Multiple children aged in over time through LLC. FICA-exempt employment under parent's disregarded entity. Each earns up to standard deduction (~$16k). State workers comp exemption pending verification.",
    tags: ["family-employment", "minor-children", "llc", "state-wc"],
  },
  {
    id: "ADR-013",
    number: "013",
    title: "Operator Identity & Cross-Domain Mastery Profile",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent record. Identity layer. Does not expire.",
    date: "2026-03-29",
    domain: "identity",
    position: "Permanent",
    dependsOn: [],
    summary: "Generalized mastery architecture: 40 years violin → YY Method → cross-domain CTO/COO/CFO. Human captures. AI reads. Parallel sessions on same day (tax + device architecture) demonstrate methodology portability.",
    tags: ["identity", "mastery", "yy-method", "permanent"],
  },
  {
    id: "ADR-014",
    number: "014",
    title: "Employer Profit-Sharing Contribution Strategy",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires pending employer conversation and year-end numbers",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-003"],
    summary: "Target ~$8,000–10,000 employer profit-sharing contribution at year-end. Conversation with employer's decision maker required. Opens additional 401(k) space toward the annual combined limit.",
    tags: ["profit-sharing", "employer", "year-end"],
  },
  {
    id: "ADR-015",
    number: "015",
    title: "HSA Cash Deployment & Backdoor Roth Sequencing",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "HSA expires when cash deployed. Backdoor Roth expires when IRA rollover confirmed.",
    date: "2026-03-29",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-005", "ADR-007"],
    summary: "Deploy HSA idle cash → index funds (5 minutes, decades of compounding). Backdoor Roth sequence: IRA → 401(k) rollover first, then ~$14k/yr (~$7k each) tax-free compounding. Pro-rata blocker must clear first.",
    tags: ["hsa", "backdoor-roth", "index-funds", "ira-rollover"],
  },
  {
    id: "ADR-016",
    number: "016",
    title: "AI Capability Assessment — March 2026",
    status: "Permanent Record",
    freshness: "Permanent",
    freshnessNote: "Never expires as historical record. Dated snapshot of AI capability.",
    date: "2026-03-29",
    domain: "agent",
    position: "Permanent",
    dependsOn: ["ADR-013"],
    summary: "Evidence-based AI capability snapshot: operator caught 4 model errors. Model supplied mechanics, arithmetic, platform details. Human captures. AI reads. Version history is the evidence. Preserve all zips — scars are the truth.",
    tags: ["ai-capability", "evidence", "version-history", "permanent"],
  },
  {
    id: "ADR-017",
    number: "017",
    title: "Case Study Methodology — Illustrative Framing Notice",
    status: "Permanent Record",
    freshness: "Permanent",
    freshnessNote: "Permanent. Governs interpretation of the full ADR set.",
    date: "2026-03-29",
    domain: "methodology",
    position: "Permanent",
    dependsOn: ["ADR-013"],
    summary: "This ADR set is a case study demonstrating the YY Method™ Home Edition v2.3. Numbers are illustrative, institution names genericized, identifying details adjusted. Dates and structural logic preserved. Not financial advice.",
    tags: ["case-study", "disclaimer", "methodology", "framing"],
  },
  {
    id: "ADR-018",
    number: "018",
    title: "Search, Tag Cloud & Organic Discovery — SEO/AEO/GEO Strategy",
    status: "Pending",
    freshness: "Pending",
    freshnessNote: "Trigger: 3+ case studies published, or explicit Phase 2 decision.",
    date: "2026-03-30",
    domain: "methodology",
    position: "Forward-looking",
    dependsOn: ["ADR-017"],
    summary: "Intent-based search with tag cloud hints deferred to Phase 2. SEO/AEO/GEO foundations (static HTML, robots.txt, sitemap) immediate. Full structured data, FAQ markup, and LLM optimization after archive reaches sufficient depth.",
    tags: ["search", "seo", "aeo", "geo", "tag-cloud", "organic-discovery", "phase-2"],
  },
  {
    id: "ADR-019",
    number: "019",
    title: "Pro-Rata Rule — System Non-Negotiable",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Expires if IRS changes pro-rata mechanics or IRA basis situation changes.",
    date: "2026-03-30",
    domain: "tax",
    position: "Cross-cutting",
    dependsOn: ["ADR-005", "ADR-015"],
    summary: "Pre-tax IRA balance must equal $0 on December 31 each year. Without this, pro-rata rule makes backdoor Roth conversions partially taxable. IRA is 100% pre-tax — no basis to preserve, clean full rollover is optimal.",
    tags: ["pro-rata", "backdoor-roth", "ira", "non-negotiable", "roth-conversion"],
  },
  {
    id: "ADR-020",
    number: "020",
    title: "IRA → Employer 401(k) Rollover — Phase 1 One-Time Cleanup",
    status: "Decided",
    freshness: "Pending",
    freshnessNote: "Expires when rollover confirmed complete for both spouses. One-time execution.",
    date: "2026-03-30",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-019", "ADR-005"],
    summary: "Roll full Traditional and SEP IRA balances → employer 401(k) for both spouses. Solo 401(k) rejected for Phase 1: plan custodian requires physical check, 1–2 weeks out of market. Employer plan accepts direct transfer. Convert any small leftover to Roth. Verify $0 by Dec 31.",
    tags: ["ira-rollover", "employer-401k", "pro-rata-cleanup", "phase-1", "one-time"],
  },
  {
    id: "ADR-021",
    number: "021",
    title: "Backdoor Roth Annual Cycle — Phase 2 Repeating System",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Expires if IRA contribution limits change, conversion rules change, or IRA balance is not $0 on Dec 31.",
    date: "2026-03-30",
    domain: "tax",
    position: "Derived",
    dependsOn: ["ADR-019", "ADR-020"],
    summary: "Three steps per person per year: (1) contribute ~$7k non-deductible to Traditional IRA, (2) convert immediately to Roth IRA, (3) file Form 8606. ~$0 tax. ~$14k/year combined Roth funding. IRA is an empty pipe — never held, always converted.",
    tags: ["backdoor-roth", "form-8606", "roth-ira", "annual-cycle", "phase-2"],
  },
  {
    id: "ADR-022",
    number: "022",
    title: "Employer 401(k) vs Solo 401(k) — Simplicity First, Optionality Preserved",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Expires if employment ends, LLC income grows materially, or employer plan quality degrades.",
    date: "2026-03-30",
    domain: "tax",
    position: "Forward-looking",
    dependsOn: ["ADR-019", "ADR-005"],
    summary: "Use employer 401(k) as primary pre-tax vehicle — quality index funds, low fixed fee, accepts rollovers, zero admin. Solo 401(k) deferred until LLC income warrants employer contributions or mega backdoor Roth is configured. Employer 401(k) rolls into solo 401(k) if employment ends — nothing foreclosed.",
    tags: ["employer-401k", "solo-401k", "mega-backdoor", "llc", "optionality"],
  },
  {
    id: "ADR-023",
    number: "023",
    title: "Solo 401(k) Eligibility Correction — LLC Self-Employment Income",
    status: "Decided — Correction",
    freshness: "Permanent",
    freshnessNote: "Permanent correction record. Supersedes two specific claims in ADR-005.",
    date: "2026-03-30",
    domain: "tax",
    position: "Correction",
    dependsOn: ["ADR-005"],
    summary: "Corrects ADR-005: solo 401(k) is NOT frozen after S corp terminates. LLC (disregarded entity) can sponsor the plan; contribution basis becomes net SE income. Employee deferral ($23,500) + employer (~20% SE income) available — far superior to SEP-IRA at the same income. IRA rollover window also remained open. ADR-020–022 decisions unchanged.",
    tags: ["solo-401k", "llc", "se-income", "correction", "sep-ira", "adr-005"],
  },
  {
    id: "ADR-025",
    number: "025",
    title: "FICA Correction — Full Payroll Tax on Final Bonus",
    status: "Decided — Correction",
    freshness: "Permanent",
    freshnessNote: "Permanent correction record. Standing principle: do not act on future wage information to determine current FICA obligations.",
    date: "2026-03-31",
    domain: "tax",
    position: "Correction",
    dependsOn: ["ADR-002"],
    summary: "Corrects ADR-002: FICA on the final bonus is full 15.3% (7.65% employee + 7.65% employer), not Medicare-only. S corp YTD W-2 was ~$60k at bonus time — below the SS wage base. Future employer W-2 is not a valid basis for reducing current FICA deposits. Employee FICA must also be withheld from gross before net pay is calculated.",
    tags: ["fica", "payroll", "ss-wage-base", "correction", "adr-002", "employee-fica"],
  },
  {
    id: "ADR-024",
    number: "024",
    title: "Build Session — yymethod-home-v1, March 30, 2026",
    status: "Permanent Record",
    freshness: "Permanent",
    freshnessNote: "Permanent historical record. Documents how this site was built on the day it was completed.",
    date: "2026-03-30",
    domain: "methodology",
    position: "Permanent",
    dependsOn: ["ADR-013", "ADR-016", "ADR-017"],
    summary: "Full build session record: case study selector home page, /case-001 URL structure, ADR-019 through ADR-023, HTTPS DNS diagnosis, discrepancy audit, correction ADR filed. What broke, how it was fixed, and why none of it is magic — it is hardened dev practice applied with intention. AI is a force multiplier for disciplined operators.",
    tags: ["build-session", "methodology", "corrections", "discipline", "permanent", "ai-tooling"],
  },
];

export function getADR(id: string): ADR | undefined {
  return adrs.find((a) => a.id === id);
}

export function getADRsByDomain(domain: ADR["domain"]): ADR[] {
  return adrs.filter((a) => a.domain === domain);
}

export function getADRsByStatus(status: ADRStatus): ADR[] {
  return adrs.filter((a) => a.status === status);
}

export const statusColor: Record<ADRStatus, string> = {
  "Decided": "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
  "Decided — Rejected": "bg-red-500/15 text-red-400 border-red-500/20",
  "Decided — Correction": "bg-amber-500/15 text-amber-400 border-amber-500/20",
  "Decided — Partially Corrected": "bg-orange-500/15 text-orange-400 border-orange-500/20",
  "Pending": "bg-blue-500/15 text-blue-400 border-blue-500/20",
  "Permanent Record": "bg-violet-500/15 text-violet-400 border-violet-500/20",
  "AI Extrapolated": "bg-rose-500/15 text-rose-400 border-rose-500/20",
};

export const domainLabel: Record<ADR["domain"], string> = {
  tax: "Tax",
  identity: "Identity",
  agent: "Agent",
  device: "Device",
  methodology: "Methodology",
};
