import type { ADRStatus } from "@/lib/adrs";

export type ADRCase008Domain = "framing" | "integrity" | "analysis" | "strategy" | "execution" | "posture";

export interface ADRCase008 {
  id: string;
  number: string;
  title: string;
  status: ADRStatus;
  freshness: "Active" | "Permanent" | "Pending";
  freshnessNote: string;
  date: string;
  domain: ADRCase008Domain;
  position: "Foundational" | "Derived" | "Correction" | "Cross-cutting";
  dependsOn: string[];
  summary: string;
  tags: string[];
}

export const adrsCase008: ADRCase008[] = [
  {
    id: "C8-001",
    number: "001",
    title: "Framing — The Game as a Judgment-Under-Constraint Problem",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The framing argument does not expire. Any iteration of this game format produces the same class of decisions.",
    date: "2026-04-25",
    domain: "framing",
    position: "Foundational",
    dependsOn: [],
    summary: "A Scrabble-variant charity/community tournament with a 20-minute time limit, open theme constraints, premium-square scoring, informal governance, and no live referee is not recreational Scrabble. It is a judgment problem: optimization under real-world constraint with incomplete information, time pressure, adversarial interpretation risk, and structural enforcement gaps. The correct frame is competitive decision-making under constrained rules — not a vocabulary showcase, not a pure combinatorial puzzle, not a social game where results don't matter. Each decision carries consequences. The operator who treats it as casual play leaves preparation value on the table. The operator who treats it as a solved optimization problem ignores the human factors that dominate the actual outcome.",
    tags: ["framing", "judgment-under-constraint", "competitive-decision-making", "rule-governance", "informal-enforcement", "foundational-premise"],
  },
  {
    id: "C8-002",
    number: "002",
    title: "Prior 2nd Place as Signal, Not Grievance",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The methodological point — that an unexpected result licenses a systematic review — does not expire. The specific prior result is the input to this case, not the output.",
    date: "2026-04-25",
    domain: "framing",
    position: "Derived",
    dependsOn: ["C8-001"],
    summary: "The 2nd place finish was unexpected given prior competitive history: three wins in the previous four years, extensive preparation, and strong baseline word-game performance. The correct response to an unexpected result is not grievance (which shuts down learning) and not dismissal (which forfeits the signal). The correct response is a structured review of what the result reveals about gaps in strategy, governance, and execution. This case is that review. The 2nd place result is treated as a license to ask two questions: what did the preparation miss, and what did the game format permit that the preparation did not account for?",
    tags: ["prior-result", "signal-not-grievance", "competitive-history", "three-of-four-wins", "systematic-review", "unexpected-outcome"],
  },
  {
    id: "C8-003",
    number: "003",
    title: "Emotional Calibration — Separate Competitive Frustration from Structural Evidence",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The discipline of separating emotional response from analytical argument is a durable principle, not specific to this game.",
    date: "2026-04-25",
    domain: "framing",
    position: "Derived",
    dependsOn: ["C8-001", "C8-002"],
    summary: "The operator scores 300–400 in regular Scrabble, occasionally 500, rarely below 300. Boggle produces near-universal wins by large margins. This track record creates a calibrated self-model of competitive edge in word games under time pressure. When that expectation is violated, two things happen simultaneously: genuine emotional frustration (I usually win this) and legitimate analytical suspicion (something may be wrong with the scoring). The error is letting them collapse into each other — treating the frustration as evidence of wrongdoing, or suppressing the analytical question because raising it feels like sore-loser behavior. The discipline: frustration is real and not shameful. It is not evidence. The structural evidence stands independently of how it feels to lose. Both threads must be named and separated before either can be examined clearly.",
    tags: ["emotional-calibration", "competitive-frustration", "structural-evidence", "self-awareness", "sore-loser-risk", "separation-of-concerns"],
  },
  {
    id: "C8-004",
    number: "004",
    title: "Accidental Multiplier Reuse — The Charitable Hypothesis",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The hypothesis is the operative position absent evidence of intentional misreporting. The principle of leading with the charitable explanation is a durable methodological commitment.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Foundational",
    dependsOn: ["C8-001"],
    summary: "If a score above 2,500 was produced in this game format under these conditions, the most probable explanation is accidental reuse of premium square multipliers — specifically Triple Word multipliers already consumed by a prior word on the same square. In an informal event with self-managed scorecards and end-of-round validation, this error is easy to make and easy to miss. The alternative explanation — deliberate score inflation — is more damaging and less supported by available evidence. The default position, held explicitly and stated when relevant, is the charitable one: accidental error, not fraud. This is not a position of denial. It is a position of proportionality. The evidence licenses structural concern; it does not license an accusation of bad faith.",
    tags: ["charitable-hypothesis", "accidental-error", "multiplier-reuse", "scorecard-error", "informal-governance", "proportionality", "not-cheating"],
  },
  {
    id: "C8-005",
    number: "005",
    title: "Premium Square Exhaustion — The Core Scoring Invariant",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Standard Scrabble rules on premium square usage are stable and do not expire. This invariant governs all scoring calculations in this case.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Foundational",
    dependsOn: ["C8-004"],
    summary: "Under standard Scrabble rules, a premium square may only be used once: the first word to land on that square receives the multiplier (Double Letter, Triple Letter, Double Word, Triple Word). Every subsequent word that passes through the same square — extensions of the same word, cross-words, new plays — receives face tile value only. This is the core scoring invariant from which all plausibility analysis flows. A word scored at 27x requires spanning three Triple Word squares simultaneously. A word scored at 9x requires spanning two Triple Word squares (outer and inner, sharing a row). If a prior word has already landed on one of those squares, the multiplier is exhausted and the subsequent play cannot access it. Every calculation in this case that asks \"is this score plausible\" begins with this invariant applied to the specific board geometry.",
    tags: ["premium-square-exhaustion", "triple-word-once", "scoring-invariant", "rule-integrity", "9x", "27x", "board-geometry"],
  },
  {
    id: "C8-006",
    number: "006",
    title: "27x Plays Are Geometry-Constrained, Not Merely Vocabulary-Constrained",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Standard 15×15 board geometry does not change. The constraint is structural.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Derived",
    dependsOn: ["C8-005"],
    summary: "A 27x multiplier requires a single word to span three Triple Word squares simultaneously. On a standard 15×15 board, Triple Word squares sit at the four corners and four midpoint edges. Spanning three of them with a single word requires landing across the full width or height of the board — a 15-letter word filling an entire row or column through a triple lane. The board contains a limited number of triple lanes. More than two clean 27x plays on a single board requires extraordinary alignment: two available triple lanes, each with a 15-letter legal word that fits the available tiles, the board routing compatible with both, and both executed under time pressure with theme constraints. The vocabulary requirement compounds on top of the geometry requirement. The ceiling is not mathematically zero. It is functionally close to it under event conditions.",
    tags: ["27x-constraint", "triple-lane", "board-geometry", "15-letter-words", "geometric-ceiling", "functional-improbability"],
  },
  {
    id: "C8-007",
    number: "007",
    title: "Letter Buying Cannot Explain Repeated Premium Square Access",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The logical relationship between tile composition and premium square access is fixed by the rules.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Derived",
    dependsOn: ["C8-006"],
    summary: "Players may buy extra letters for $5 each. Buying letters increases tile pool depth and enables higher-value letter combinations. This is a real strategic lever. It explains access to tiles like Z, Q, X, and J that may not be in the standard tile distribution — enabling higher face-value plays. What it does not explain: access to premium square multipliers on squares already consumed by prior words. Premium square eligibility is determined by board position and usage sequence, not tile composition. A player who buys ten letters has not purchased access to Triple Word squares already occupied. Letter buying explains higher-value letters on eligible bonus squares. It does not explain 27x multipliers where the squares were already used. These are independent dimensions of scoring.",
    tags: ["letter-buying", "tile-composition", "premium-square-independence", "buying-rebuttal", "5-dollars-per-tile", "logical-separation"],
  },
  {
    id: "C8-008",
    number: "008",
    title: "Score Above 2,500 as Functionally Improbable for Unprepared Participants",
    status: "Decided — Partially Corrected",
    freshness: "Active",
    freshnessNote: "Active. Reverify if the game format changes significantly — extended time limit, formal scoring referee, pre-registration of word lists — any of which would change the plausibility ceiling.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Derived",
    dependsOn: ["C8-006", "C8-007"],
    summary: "Partially corrected post-event. Original claim: the operator's prior benchmark of ~1,500 was 'the ceiling of systematic preparation,' making 2,500+ functionally improbable. The current year's result (C8-031) showed the operator executing 27x plays on every board and scoring well above 1,500 under fully rule-compliant play — proving the 1,500 ceiling was the prior preparation approach's ceiling, not rule-compliant play's ceiling. Corrected claim: scores above 2,500 are functionally improbable for participants without the Boggle/Scrabble skill combination. They are achievable for those with it. The prior year's anomalous result was produced by participants without that combination, making accidental error (C8-004) more probable than extraordinary legitimate play — a conclusion the current year's result strengthens rather than undermines.",
    tags: ["2500-score", "functional-improbability", "participant-specific", "unprepared-baseline", "boggle-scrabble-threshold", "charitable-hypothesis-strengthened", "partially-corrected"],
  },
  {
    id: "C8-009",
    number: "009",
    title: "Personal 1,500-Point Score as Calibrated Benchmark — Superseded by Current Year",
    status: "Decided — Partially Corrected",
    freshness: "Active",
    freshnessNote: "Active. Benchmark updated post-event: the current year's result significantly exceeded 1,500 using the evolved Boggle/Scrabble strategy with 27x plays on every board.",
    date: "2026-04-25",
    domain: "analysis",
    position: "Derived",
    dependsOn: ["C8-008"],
    summary: "The approximately 1,500-point prior benchmark was the ceiling of the 15-letter-first preparation approach, not the ceiling of rule-compliant play. Post-event correction: the current year's result significantly exceeded this benchmark as the operator applied the Boggle/Scrabble combination with 27x plays on every board (C8-031). The 1,500 figure is now a historical reference point for the prior preparation approach. Its value for the plausibility analysis in C8-008 is precisely that it established a baseline for unprepared and partially-prepared participants — the prior year's anomalous result still carries a heavy burden of explanation relative to that baseline, because the participants who produced it did not demonstrate the skill combination the current year showed is required.",
    tags: ["1500-benchmark", "superseded", "prior-preparation-ceiling", "current-year-exceeded", "historical-reference", "plausibility-anchor"],
  },
  {
    id: "C8-010",
    number: "010",
    title: "Correction — AI Miscounted the 15-Letter Words; Operator Challenge Caught It",
    status: "Decided — Correction",
    freshness: "Permanent",
    freshnessNote: "Permanent scar record. LLMs have a documented, persistent weakness with letter counting. The discipline of challenging AI counts does not expire.",
    date: "2026-04-25",
    domain: "analysis",
    position: "Correction",
    dependsOn: [],
    summary: "During AI-assisted preparation, the LLM proposed PREQUALIFICATIONS, INSTITUTIONALIZING, and DECRIMINALIZATION as 15-letter candidates for triple-lane play. All three are wrong: PREQUALIFICATIONS is 17 letters, INSTITUTIONALIZING is 18, DECRIMINALIZATION is 17. The operator challenged the AI's counts and caught the errors before they entered game execution. This is a documented LLM failure mode: large language models process tokens, not characters, and their letter counts are pattern-matched guesses, not enumeration — they are confidently wrong on simple counting tasks with no sign of uncertainty. The error recurred across multiple words and multiple prompts, confirming it as a systematic AI weakness, not a one-time hallucination. The first version of this ADR also recorded the counts as 16 — an AI error in an ADR about AI errors, caught on review. The mandatory discipline: every AI-generated word count must be independently verified by manual count or dictionary lookup before entry into the candidate set. Never accept an LLM's stated letter count as ground truth. Challenge it every time.",
    tags: ["letter-count", "correction", "ai-miscounting", "llm-counting-weakness", "challenge-ai-output", "prequalifications-error", "scar-record", "operator-caught", "17-letter-error"],
  },
  {
    id: "C8-011",
    number: "011",
    title: "15-Letter Words Reframed as Opportunistic Upside, Not Core Strategy",
    status: "Decided — Partially Corrected",
    freshness: "Permanent",
    freshnessNote: "Permanent. The correction from core-strategy to opportunistic-upside is a structural reframe, not a tactical adjustment.",
    date: "2026-04-25",
    domain: "strategy",
    position: "Derived",
    dependsOn: ["C8-010"],
    summary: "Initial preparation treated memorizing 15-letter words as the core strategic investment for a potential 27x play. This was a category error. The conversion rate from 'known 15-letter word' to 'successfully executed triple-lane 27x play' requires a conjunction of four conditions: the word fits the current board layout, the triple lane is available and uncovered, the required tiles are in the current rack, and sufficient time remains. All four must hold simultaneously in a 20-minute format under theme constraints with no pre-computed routing. The probability of that conjunction is low, no matter how many 15-letter words are memorized. The corrected position: 15-letter words are maintained as prepared knowledge for opportunistic deployment. If all four conditions align, execute. If they do not align by mid-round, the primary strategy was always the 9x plan described in C8-012. The 15-letter words are the bonus track, not the setlist.",
    tags: ["15-letter-words", "opportunistic-upside", "strategy-correction", "conjunction-probability", "core-strategy-rejected", "partially-corrected"],
  },
  {
    id: "C8-012",
    number: "012",
    title: "9x + High-Value Letter Premium as the Practical Scoring Engine",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Reverify if game format changes (board size, tile distribution, premium square placement) materially alter the 9x yield calculation.",
    date: "2026-04-25",
    domain: "strategy",
    position: "Foundational",
    dependsOn: ["C8-011"],
    summary: "The practical scoring engine for this format is a word crossing one outer and one inner Triple Word square (9x multiplier) with at least one high-value tile (Z=10, Q=10, X=8, J=8) aligned on a Double Letter square within the word. A well-structured 9x play with Z on a Double Letter: the Z contributes 20 points (10 × DL), and the full word value is then multiplied by 9 (TW × TW); a word like SQUEEZING yields hundreds of points from that single play depending on exact tile placement (higher still if Q also lands on a bonus square). Two such plays in a round produce 400–700 points from primary plays alone, before standard board scoring accumulates. The 9x strategy is high-probability because: the words are shorter (8–12 letters typically), the legal word list is vastly larger, the routing is more flexible, theme justification is easier, and the geometric requirement is achievable without 15-letter precision. The 9x play is the engine. The 27x is kept available as upside.",
    tags: ["9x-strategy", "scoring-engine", "high-value-letters", "double-letter-alignment", "squeezing", "expected-value", "practical-scoring"],
  },
  {
    id: "C8-013",
    number: "013",
    title: "Round Structure — One Optimized + One Semi-Optimized Play",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if round time changes significantly or if game variant introduces different play constraints.",
    date: "2026-04-25",
    domain: "strategy",
    position: "Derived",
    dependsOn: ["C8-012"],
    summary: "The planned round structure: identify one primary optimized play (best available 9x + premium letter alignment, with 27x as bonus if conditions allow) and one secondary semi-optimized play (next-best 9x opportunity, or the strongest available play without premium lane alignment if none is reachable). This two-play structure ensures that if the primary play does not materialize, the round produces one strong play plus standard scoring rather than a failed search for an unreachable position. The round is not won on volume of plays — it is won on the expected value of the top two plays, plus whatever standard scoring accumulates. Designing around two plays prevents under-building (too few plays, insufficient board) and prevents over-complexity (too many simultaneous constraints paralyzed by optionality).",
    tags: ["round-structure", "two-play-design", "primary-optimized", "secondary-fallback", "expected-value", "prevent-paralysis"],
  },
  {
    id: "C8-014",
    number: "014",
    title: "Mid-Round Pivot Rule — Preventing Decision Paralysis",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. The rule applies whenever the round format has time pressure. Revisit only if the time limit changes substantially.",
    date: "2026-04-25",
    domain: "strategy",
    position: "Derived",
    dependsOn: ["C8-013"],
    summary: "Pivot rule: if the primary optimized play is not within one or two moves of completion at the halfway point of the round, abandon it and execute the secondary play immediately. The failure mode this addresses is attachment to a planned play that circumstances have made unreachable — spending the back half of the round chasing a position that cannot be reached in the remaining time, sacrificing board development and other scoring opportunities. Decision paralysis under time pressure costs more than executing a slightly suboptimal play earlier. The pivot rule makes the decision explicit and pre-committed so it requires no in-the-moment judgment under pressure. The word 'immediately' in the rule is intentional: pivot means switch now, not 'begin reconsidering from scratch.'",
    tags: ["pivot-rule", "decision-paralysis", "mid-round", "time-pressure", "pre-committed-decision", "attachment-failure-mode"],
  },
  {
    id: "C8-015",
    number: "015",
    title: "Physical Letter Staging — Externalizing Working Memory",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. The technique applies to any iteration of this game format.",
    date: "2026-04-25",
    domain: "execution",
    position: "Derived",
    dependsOn: ["C8-013"],
    summary: "During tile selection, physically move candidate tiles into separate category piles without placing them in word order on the board (pre-placement is not permitted). The piles serve as externalized working memory: instead of holding all tile possibilities in mind simultaneously, tiles are sorted into visible categories (high-value letters, 9x word candidates, standard scoring tiles), and decisions are made against observable piles rather than remembered inventories. The key rule: piles are categories, not words. Moving a tile into a pile does not commit it to any word. This technique reduces the cognitive load of the tile-selection phase and leaves more bandwidth for board routing and theme justification — the decisions that actually determine scoring outcome.",
    tags: ["tile-staging", "working-memory", "physical-sorting", "cognitive-load", "category-piles", "pre-placement-distinction"],
  },
  {
    id: "C8-016",
    number: "016",
    title: "Letter Buying — Only When Unlocking High-EV Multiplier Alignment",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if the cost of letter buying changes or if the scoring structure changes significantly.",
    date: "2026-04-25",
    domain: "execution",
    position: "Derived",
    dependsOn: ["C8-012"],
    summary: "Letter buying ($5 per tile) is a targeted unlock decision, not general inventory replenishment. A purchase is justified when: (a) a specific identified play requires a tile not currently in the rack, and (b) that play has a high-EV multiplier position (9x or better) with a premium letter. Buying a Z to land on a Double Letter square inside a 9x word: $5 for potentially 150–200 incremental points is strong expected value. Buying a vowel to complete a generic word with no premium alignment: $5 for minor scoring is weak expected value. The decision is always: what specific word, what specific board position, what specific premium alignment does this tile unlock? The best targets are Z, Q, X, J. Buying one or two letters to complete a known high-EV construction is justified. Buying letters speculatively to expand the general tile pool is not.",
    tags: ["letter-buying", "5-dollars", "high-ev-unlock", "premium-alignment", "targeted-purchase", "z-q-x-j", "expected-value-calculation"],
  },
  {
    id: "C8-017",
    number: "017",
    title: "Theme Interpretation — From Strict Purity to Defensible Gray Zone",
    status: "Decided — Partially Corrected",
    freshness: "Permanent",
    freshnessNote: "Permanent. The correction from strict purity to gray-zone interpretation is a structural reframe that applies to any loosely enforced theme format.",
    date: "2026-04-25",
    domain: "execution",
    position: "Foundational",
    dependsOn: ["C8-001"],
    summary: "Initial approach: only place words with clear, obvious connection to the round's assigned theme (food, transportation, science, summer, etc.). This was a corrected position. The correction: the judging is loose and happens at the end of the round, not word by word. Strict self-enforcement eliminates large portions of the legal word set without producing any competitive advantage, because the actual adjudication standard is permissive. Playing strictly while others play loosely is not moral integrity — it is unilateral self-handicap. The corrected approach: accept any word for which a one-sentence connection to the theme can be honestly constructed. The theme is a constraint on the candidate set, not a gate that only admits the most obvious words. The correction does not mean playing off-theme words. It means playing in the gray zone where the connection is real but not immediately obvious.",
    tags: ["theme-interpretation", "strict-purity-rejected", "gray-zone", "loose-enforcement", "unilateral-handicap", "partially-corrected"],
  },
  {
    id: "C8-018",
    number: "018",
    title: "The One-Sentence Theme Justification Standard",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Applies to any round with an assigned theme in this or similar game formats.",
    date: "2026-04-25",
    domain: "execution",
    position: "Derived",
    dependsOn: ["C8-017"],
    summary: "Every word placed on the board must pass a one-sentence test before placement: \"This word connects to [theme] because [single coherent reason].\" The reason must be honest — not a mental gymnastics stretch. But 'non-obvious' is acceptable; 'fabricated' is not. Examples: SQUEEZING under Food: 'You squeeze citrus fruits for juice.' MOBILIZING under Transportation: 'Mobilizing resources is the precondition for transport operations.' TECHNIQUES under Food: 'Cooking relies on mastering techniques.' MARZIPANS under Food: direct. JUNCTIONS under Transportation: direct. The sentence is a discipline tool and an audit tool — if a judge challenges a word, the sentence is ready. It prevents two failure modes: blind acceptance of anything (which creates audit risk under end-of-round judging) and reflexive rejection of defensible words (which self-handicaps). The sentence must be sayable aloud without embarrassment.",
    tags: ["one-sentence-test", "theme-justification", "audit-tool", "squeezing", "mobilizing", "marzipans", "defensible-connection"],
  },
  {
    id: "C8-019",
    number: "019",
    title: "Strict Theme Enforcement Rejected as Unilateral Self-Handicap",
    status: "Decided — Rejected",
    freshness: "Permanent",
    freshnessNote: "Permanent. The original position (strict theme enforcement) is explicitly rejected and preserved as a scar.",
    date: "2026-04-25",
    domain: "execution",
    position: "Derived",
    dependsOn: ["C8-017"],
    summary: "The initial position — apply strict theme interpretation, rejecting any word without obvious thematic connection — is explicitly rejected. The argument for strict enforcement: it is the correct reading of the rules and integrity matters. The argument against: the rules specify thematic connection, not strict-obvious connection; the judges interpret loosely; no external enforcement supports the strict standard; and the cost (reduced word set, reduced scoring) is borne entirely by the self-enforcing player while producing no competitive benefit and no governance improvement. Strict enforcement, applied unilaterally in an environment where the standard is not enforced, converts a discipline into a handicap. The correct response to loose enforcement is not to match it without limit — it is to operate in the defensible gray zone with a one-sentence justification standard (C8-018), not in a self-imposed narrower zone that no one else is applying.",
    tags: ["strict-enforcement-rejected", "scar-record", "unilateral-handicap", "theme-integrity", "defensible-not-strict", "rejected-position"],
  },
  {
    id: "C8-020",
    number: "020",
    title: "Delayed Judging as a Structural Weakness in the Game Format",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Applies to any iteration of this game format with end-of-round judging. Reverify if format changes to include real-time adjudication.",
    date: "2026-04-25",
    domain: "integrity",
    position: "Derived",
    dependsOn: ["C8-005", "C8-017"],
    summary: "Theme compliance is adjudicated at the end of the round, after all words are placed and the board is complete. This creates a structural cascade problem: if a judge rejects a load-bearing word after play concludes, words that were built extending or crossing it may also be invalidated, collapsing a significant portion of the board's scoring. The player who placed the ambiguous word accepted the downstream cascade risk at placement time without knowing how the judge would rule. Delayed judging also fails to catch premium square reuse in the moment — errors that would be caught by a live referee go unnoticed until a player or observer reviews the scorecard. The structural mitigation is pre-play clarification (C8-021), not hope that the delay will resolve cleanly.",
    tags: ["delayed-judging", "structural-weakness", "cascade-risk", "end-of-round", "board-collapse", "real-time-adjudication-absent"],
  },
  {
    id: "C8-021",
    number: "021",
    title: "Pre-Clarify Rules Before Play, Not After Results",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Applies to every tournament iteration. The principle does not expire.",
    date: "2026-04-25",
    domain: "posture",
    position: "Foundational",
    dependsOn: ["C8-004", "C8-020"],
    summary: "Any question about rule interpretation — premium square reuse, theme standards, tile-count limits, valid word sets — must be raised before play begins, framed as clarification, not accusation. After results are announced, raising a challenge reads as sore-loser behavior regardless of its merit, triggers defensiveness, and has no resolution mechanism in an informal community event. Before play, the same questions are competent due diligence: 'Can you clarify how triple-word squares work when a later word passes through a square a prior word already used?' This is not suspicious — it is methodical. The failure to ask this question before the prior tournament is the specific gap that the 2nd place finish licenses fixing. Pre-clarification protects the game as well as the player: when everyone understands the rule before play, accidental scoring errors become less likely.",
    tags: ["pre-clarification", "before-not-after", "rule-questions", "due-diligence", "not-accusation", "challenge-cost", "governance-repair"],
  },
  {
    id: "C8-022",
    number: "022",
    title: "Winning Board Display as Celebration and Soft Audit",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. The proposal should be made at setup for each tournament iteration.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-021"],
    summary: "Proposed mechanism: at the end of the tournament, winning boards are displayed for everyone to see. The framing is celebratory: 'It would be fun if the winning boards were displayed at the end so everyone can see how people scored and learn from each other.' The mechanism this creates: genuine celebration of strong play (a well-constructed board is worth showing); natural community audit (players who understand the scoring rules can observe whether the score is geometrically consistent with what the board shows); and deterrence against future accidental errors (awareness that the board will be visible creates incentive for careful self-scoring). The proposal requires no accusation, invites no confrontation, and benefits the game regardless of whether any prior scoring was irregular. The board should speak.",
    tags: ["board-display", "soft-audit", "celebratory-framing", "transparency-mechanism", "learn-from-each-other", "board-should-speak"],
  },
  {
    id: "C8-023",
    number: "023",
    title: "Post-Event Notification and the Commitment Not to Relitigate",
    status: "Decided — Correction",
    freshness: "Permanent",
    freshnessNote: "Permanent. The distinction between clean notification and adversarial relitigating does not expire.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-003", "C8-008"],
    summary: "Operator-corrected ADR. The AI's version stated 'no retroactive complaint to organizers' and argued against raising the concern informally — both wrong. Corrected record: same-day evening after the prior tournament, the operator sent an informational email to the organizers explaining how premium square scoring works and describing what likely happened with the anomalous result. The email did not request any change to the prior year's result. Organizers acknowledged it. The subsequent year's governance improvements (detailed scoring guide, removal of format ambiguities) are the inferred — not confirmed — response. 'Not relitigating' means: one clean notification to the responsible party, no social discussion, no ongoing pursuit after acknowledgment. It does not mean silence toward the people who can act on the information.",
    tags: ["post-event-email", "notification-not-challenge", "no-relitigate", "informational", "organizers-acknowledged", "ai-correction", "responsibility-channel"],
  },
  {
    id: "C8-024",
    number: "024",
    title: "The 2nd Place Medal as a Prompt to Speak Earlier",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. The prompt applies to each tournament iteration until the behaviors it encodes become automatic.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-002", "C8-003"],
    summary: "The 2nd place medal is not a symbol of failure. It is a concrete reminder of three specific gaps in prior execution: rule-clarification questions were not raised before play; a board-display proposal was not made at setup; and in-the-moment scoring concerns were not surfaced when they arose. These are the correctable errors. The medal's function is practical: it encodes three prompts. Before play — ask about premium square rules and theme standard. At setup — propose winning board display. During play — speak in the moment if scoring appears inconsistent. The medal is not sentimental; it is operational. The preparation this year is not just better words and better geometry — it is better judgment about when to speak.",
    tags: ["medal-as-prompt", "speak-earlier", "three-specific-gaps", "correctable-errors", "operational-reminder", "judgment-improvement"],
  },
  {
    id: "C8-025",
    number: "025",
    title: "Clean Defeat — What a Legitimate Win by Another Player Looks Like",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The definition of a clean win is a stable standard that applies to every tournament iteration.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-023", "C8-026"],
    summary: "If a player or team beats the operator at the next tournament with a clean score, that result is accepted without complaint. A clean score is defined operationally: it can be read from the physical board with proper premium square application, the score is consistent with available tile counts (adjusted for any purchased letters), and the board layout is geometrically plausible for the multipliers claimed. A board that passes these checks deserves its score. Losing to it is legitimate competitive defeat — and accepting it without qualification is the standard that makes the operator's own wins credible. The commitment to accept clean defeat is not weakness. It is the reciprocal of the commitment to win clean.",
    tags: ["clean-defeat", "legitimate-loss", "accept-without-complaint", "clean-score-definition", "board-readable", "reciprocal-standard"],
  },
  {
    id: "C8-026",
    number: "026",
    title: "Clean Victory — Win Under Objective Constraints, Not Ambiguity",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The standard for a win worth keeping does not expire.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-005", "C8-021"],
    summary: "The operator's own play must meet the same standard it applies to others. A clean victory means: every premium square multiplier applied correctly (no reuse), every word in the legal word list (Scrabble dictionary / CSW / SOWPODS), every theme word defensibly justifiable under the one-sentence standard (C8-018), and the scoring verifiable from the physical board without supplementary explanation. The value of a clean win is not only the medal — it is the ability to display the board, explain every point, and invite scrutiny. A win that cannot withstand a display and a read-through is not a win to stand behind. The board should speak. If someone audits the scorecard against the board, the score should hold exactly.",
    tags: ["clean-victory", "auditable-win", "board-readable", "no-multiplier-reuse", "one-sentence-standard", "invite-scrutiny"],
  },
  {
    id: "C8-027",
    number: "027",
    title: "Play the Actual Game Being Run, Not the Idealized Version",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Applies to every iteration of this game format as long as governance remains informal.",
    date: "2026-04-25",
    domain: "posture",
    position: "Foundational",
    dependsOn: ["C8-017", "C8-021"],
    summary: "The game as actually administered differs from the game as designed. In the actual game: theme is loosely enforced; judging happens at the end; premium square reuse may go undetected without active scoring attention; the social environment is community-charitable. The idealized game is strictly refereed, immediately adjudicated, and formally scored. Playing the idealized game inside the actual game means optimizing for a version of the rules that does not exist in practice. The corrected posture is to play the game that is actually running: apply the one-sentence theme standard rather than strict purity; ask pre-clarification questions; speak in the moment about scoring when needed; propose board display for transparency. This is not abandoning integrity — it is reading the operational reality accurately. The work is to make the actual game better, not to play alone in the idealized one.",
    tags: ["actual-game-vs-ideal", "operational-reality", "informal-governance", "playing-the-right-game", "improve-the-actual-game", "accuracy-over-idealism"],
  },
  {
    id: "C8-028",
    number: "028",
    title: "Final Operating Posture for the Next Tournament",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit and update after each tournament iteration based on what the actual game format presented.",
    date: "2026-04-25",
    domain: "posture",
    position: "Cross-cutting",
    dependsOn: ["C8-012", "C8-027"],
    summary: "The complete operating posture: (1) Before play — ask the organizer to clarify premium square rules and theme standard; propose winning board display as a celebration mechanic. (2) During tile selection — use physical staging to externalize working memory; identify primary 9x play and secondary fallback simultaneously. (3) During board construction — apply the pivot rule at the mid-round mark; apply the one-sentence theme test before every placement; speak in the moment if scoring appears inconsistent with the rules. (4) At scoring — verify own board is clean before submitting; confirm every premium multiplier was applied only once. (5) At results — accept clean defeat without complaint; display clean win with pride. The posture is aggressive competitive play inside clean execution. Preparation, word-game calibration, scoring geometry knowledge, and tile-staging discipline should produce the competitive edge. The board should speak for itself.",
    tags: ["final-posture", "operating-checklist", "before-during-after", "aggressive-clean-play", "board-should-speak", "tournament-execution"],
  },
  {
    id: "C8-029",
    number: "029",
    title: "Letter Buying as a Charitable Multiplier — Competitive Inspiration Without Compulsion",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The principle — that visible competitive enthusiasm in a charity event can benefit the organization without coercing participants — is stable across iterations of this format.",
    date: "2026-04-25",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-016", "C8-027"],
    summary: "In a charity event, every letter purchased at $5 is a direct contribution to the organization's fundraising goal. When the operator buys letters strategically and scores well, the visible outcome — a high-scoring board, an enthusiastic account of how a Z tile was worth every penny — can inspire other participants to buy letters themselves. This is a genuine charitable multiplier: competitive play raises the floor of total donations. The distinction that governs the social execution is between inspiration and compulsion. Enthusiastically using the mechanic and sharing the enjoyment of it is inspiration; pressuring other players to buy letters to remain competitive is coercion, which undermines the voluntary spirit of the event. The correct posture is to play with visible enthusiasm for the letter-buying mechanic, offer commentary that invites without pressuring, and let the table's energy do the rest.",
    tags: ["charitable-multiplier", "letter-buying-cascade", "inspiration-not-compulsion", "charity-context", "sportsmanship", "fundraising-benefit", "voluntary-spirit"],
  },
  {
    id: "C8-030",
    number: "030",
    title: "Prior Anomaly Resolved — Rule Clarification as Retroactive Structural Evidence",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The prior anomaly is resolved. This record does not require further update.",
    date: "2026-04-26",
    domain: "integrity",
    position: "Derived",
    dependsOn: ["C8-004", "C8-005", "C8-023"],
    summary: "Between the prior year and the current year, the organizers introduced detailed scoring guidance (including a PowerPoint presentation) and substantially reduced the format's ambiguities. The operator's post-event email (C8-023) — describing the premium square rule and the likely cause of the anomalous result — is the inferred catalyst for these improvements; the organizers acknowledged the email and the subsequent changes specifically addressed what was raised. The connection is assumed, not confirmed. The prior anomaly is attributed to accidental misapplication under an ambiguous format, consistent with C8-004. A rule that required a PowerPoint to clarify is a rule that was not reliably enforced before. The integrity question is resolved.",
    tags: ["prior-anomaly-resolved", "rule-clarification", "powerpoint-scoring-guide", "email-catalyst-inferred", "charitable-hypothesis-confirmed", "governance-improvement", "case-closed"],
  },
  {
    id: "C8-031",
    number: "031",
    title: "Solvability Finding — Near-Deterministic Dominance Under Full Optimization",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The structural property of the system does not change unless the event format is substantially redesigned.",
    date: "2026-04-26",
    domain: "analysis",
    position: "Derived",
    dependsOn: ["C8-009", "C8-012"],
    summary: "Operator-corrected ADR. The AI's initial version stated the result was achieved without 27x plays and the 9x engine alone was sufficient — a smoothing error derived from prior ADRs that framed 27x as preparation-strategy upside rather than predicting execution outcome. Corrected record: every board produced a 27x multiplier. The combination of Boggle-speed tile pattern recognition (adaptive scanning under time pressure) and Scrabble geometric routing (word knowledge, premium square positioning) made 27x consistently executable. Boggle scanning found 15-letter possibilities that advance memorization alone would have missed; Scrabble geometry routed them for the multiplier. The preparation strategy not to plan around 27x was correct; the execution outcome exceeded the floor that strategy set. The AI confused preparation posture with execution result — the same class of error as C8-010. Operator challenge was required.",
    tags: ["solvability-finding", "27x-every-board", "boggle-scrabble-combination", "ai-smoothing-error", "operator-corrected", "preparation-vs-execution", "near-deterministic-dominance"],
  },
  {
    id: "C8-032",
    number: "032",
    title: "No Intentional Underperformance — The Integrity Constraint Is Symmetric",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The symmetry argument does not expire.",
    date: "2026-04-26",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-031"],
    summary: "Intentional underperformance — deliberately scoring less than full capability to engineer a closer competitive result — is rejected on integrity grounds. The argument that scores should reflect legitimate play applies symmetrically: it governs inbound claims (others must score honestly) and outbound behavior (the operator must also score honestly). Engineering a false competitive narrative by sandbagging is a form of deception in the same structural category as claiming points not earned. The discomfort of near-deterministic dominance is a system-level problem that requires a system-level response, not a behavioral compromise.",
    tags: ["no-sandbagging", "integrity-symmetric", "intentional-underperformance-rejected", "honest-scoring", "system-level-problem"],
  },
  {
    id: "C8-033",
    number: "033",
    title: "Full Optimization Disclosure Rejected — Preserving the Event's Accessibility",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The reasoning about accessibility and event character does not expire.",
    date: "2026-04-26",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-031", "C8-032"],
    summary: "Publicly sharing the full optimization system — scoring geometry, candidate word lists, strategic framework — is rejected. The event is a charitable, social activity attended by participants who are not there for a structured optimization exercise. Full disclosure would change the event's character: making it feel high-stakes to casual participants, removing the discovery layer that makes word competitions enjoyable, and stratifying participants sharply between those who prepared with the system and those who did not. The optimization knowledge is privately held not to preserve competitive advantage but to preserve the event's accessibility and social texture.",
    tags: ["disclosure-rejected", "event-character", "accessibility", "private-knowledge", "social-texture", "charitable-event"],
  },
  {
    id: "C8-034",
    number: "034",
    title: "Role Transition — From Direct Competitor to Coach",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. The role transition is a considered direction, not a finalized state. Revisit after the next event iteration.",
    date: "2026-04-26",
    domain: "posture",
    position: "Derived",
    dependsOn: ["C8-032", "C8-033"],
    summary: "The constraint set — no intentional underperformance, no full disclosure, near-deterministic dominance when competing directly — defines a structural problem without a behavioral solution. The structural resolution is role change: the operator transitions from direct competitor to coach or enabling team member for a junior or developing participant. The coaching role preserves integrity (the coached team competes with real preparation), reintroduces genuine uncertainty (the coached team's execution is not predetermined), and preserves the event's accessibility (knowledge is transmitted to a specific person, not broadcast). The operator's competitive stake migrates from their own board score to the development of the person being coached.",
    tags: ["role-transition", "competitor-to-coach", "genuine-uncertainty", "structural-resolution", "coaching-relationship", "junior-participant"],
  },
  {
    id: "C8-035",
    number: "035",
    title: "Public and Private Reasoning Layers — The Abstraction Architecture of This Case",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The two-layer architecture is a durable structural property of how this case is designed to be held and shared.",
    date: "2026-04-26",
    domain: "posture",
    position: "Cross-cutting",
    dependsOn: ["C8-034"],
    summary: "This case study is a public-layer artifact. It preserves the reasoning structure — the causal logic, the corrections, the reversals, the post-event findings — without including the full-fidelity private-layer operational detail. The public layer (structural arguments, reasoning method, decision logic) is transferable and is the case's intended contribution. The private layer (specific word candidate sets, calibrated benchmarks, geometric routing analysis) remains with the operator. The distinction is structural: the public layer's value is in its transferability; the private layer's value is in its specificity. An orchestration system that operates between these layers is noted as a conceptual pattern; no implementation detail is part of this record.",
    tags: ["public-layer", "private-layer", "reasoning-architecture", "abstraction", "two-layer-design", "transferable-method", "private-held"],
  },
  {
    id: "C8-036",
    number: "036",
    title: "Final Principle — On Participation in Systems You Can Solve",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. The principle is generalizable and does not expire.",
    date: "2026-04-26",
    domain: "posture",
    position: "Cross-cutting",
    dependsOn: ["C8-034", "C8-035"],
    summary: "When a participant can solve a system to near-deterministic dominance, the interesting question is no longer tactical — it is structural: what role within this system produces the best outcome for the system as a whole? Continued full-capability competition produces dominance without satisfaction. Intentional underperformance is dishonest. Full disclosure changes the system's character. Role evolution — reintroducing genuine uncertainty by changing the form of participation — is the structurally coherent response. The solver's knowledge becomes most valuable when directed at enabling others or competing where the outcome is genuinely open. The principle is domain-independent; this case is the specific instantiation.",
    tags: ["final-principle", "solvable-systems", "role-evolution", "genuine-uncertainty", "participation-ethics", "domain-independent", "generalizable-principle"],
  },
];

export function getADRCase008(id: string): ADRCase008 | undefined {
  return adrsCase008.find((a) => a.id === id);
}

export function getADRsCase008ByDomain(domain: ADRCase008Domain): ADRCase008[] {
  return adrsCase008.filter((a) => a.domain === domain);
}

export const domainLabelCase008: Record<ADRCase008Domain, string> = {
  framing: "Framing",
  integrity: "Integrity",
  analysis: "Analysis",
  strategy: "Strategy",
  execution: "Execution",
  posture: "Posture",
};
