import type { ADRStatus } from "@/lib/adrs";

export type ADRCase012Domain = "identity" | "audience" | "daily-ritual" | "coach-authority" | "method-runtime" | "memory" | "corpus" | "defensive-judgment";

export interface ADRCase012 {
  id: string;
  number: string;
  title: string;
  status: ADRStatus;
  freshness: "Active" | "Permanent" | "Pending";
  freshnessNote: string;
  date: string;
  domain: ADRCase012Domain;
  position: "Foundational" | "Derived" | "Correction" | "Cross-cutting";
  dependsOn: string[];
  summary: string;
  tags: string[];
}

export const adrsCase012: ADRCase012[] = [
  {
    id: "C12-001",
    number: "001",
    title: "Reject the Generic AI Violin Coach",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Foundational",
    dependsOn: [],
    summary: "The product will not compete primarily as a general-purpose AI violin expert capable of answering any question and generating broad practice advice.",
    tags: ["identity", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-002",
    number: "002",
    title: "Define the Missing Interval as “Between Lessons”",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Foundational",
    dependsOn: ["C12-001"],
    summary: "The product’s primary problem space is the interval between moments of human instruction.",
    tags: ["identity", "define", "violin-stand-partner"],
  },
  {
    id: "C12-003",
    number: "003",
    title: "Reject Teacher-Replacement Positioning",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Correction",
    dependsOn: ["C12-002"],
    summary: "The app will not present itself as a replacement for a qualified violin teacher.",
    tags: ["identity", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-004",
    number: "004",
    title: "Promote “Stand Partner” From Behavior to Product Identity",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Derived",
    dependsOn: ["C12-003"],
    summary: "Adopt Violin Stand Partner as the product name and organizing relationship.",
    tags: ["identity", "promote", "violin-stand-partner"],
  },
  {
    id: "C12-005",
    number: "005",
    title: "Separate Product Metaphors",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Derived",
    dependsOn: ["C12-004"],
    summary: "Use distinct metaphoric systems for distinct products.",
    tags: ["identity", "separate", "violin-stand-partner"],
  },
  {
    id: "C12-006",
    number: "006",
    title: "Define the Product’s Governing Promise",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "identity",
    position: "Foundational",
    dependsOn: ["C12-005"],
    summary: "The app’s promise is not mastery, instant diagnosis, or comprehensive instruction.",
    tags: ["identity", "define", "violin-stand-partner"],
  },
  {
    id: "C12-007",
    number: "007",
    title: "Begin With Returning and Developing Players",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "audience",
    position: "Derived",
    dependsOn: [],
    summary: "The initial self-directed audience includes returning adults and developing players who can articulate practice concerns but need continuity and structure.",
    tags: ["audience", "begin", "violin-stand-partner"],
  },
  {
    id: "C12-008",
    number: "008",
    title: "Make Parents a First-Class Audience",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "audience",
    position: "Derived",
    dependsOn: ["C12-007"],
    summary: "Parents helping children are not secondary users.",
    tags: ["audience", "make", "violin-stand-partner"],
  },
  {
    id: "C12-009",
    number: "009",
    title: "Reject Automatic Transfer of Player Advice to Parents",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "audience",
    position: "Correction",
    dependsOn: ["C12-008"],
    summary: "Advice suitable for a trained player cannot automatically be presented to a parent or novice helper.",
    tags: ["audience", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-010",
    number: "010",
    title: "Preserve Multiple Levels Without One Universal Voice",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "audience",
    position: "Derived",
    dependsOn: ["C12-009"],
    summary: "The app may support multiple levels, but the same guidance should not be delivered identically to all users.",
    tags: ["audience", "preserve", "violin-stand-partner"],
  },
  {
    id: "C12-011",
    number: "011",
    title: "Keep Action-Authorizing Launch Routes Violin-Specific",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "audience",
    position: "Derived",
    dependsOn: ["C12-010"],
    summary: "Physical-action routes at launch should remain violin-specific.",
    tags: ["audience", "keep", "violin-stand-partner"],
  },
  {
    id: "C12-012",
    number: "012",
    title: "Reject the Comprehensive Generated Practice Plan",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Correction",
    dependsOn: [],
    summary: "Do not make the daily product a large AI-generated practice plan.",
    tags: ["daily-ritual", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-013",
    number: "013",
    title: "Establish the Five-Minute Page Turn",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Derived",
    dependsOn: ["C12-012"],
    summary: "The primary daily action should generally be completable in five minutes.",
    tags: ["daily-ritual", "establish", "violin-stand-partner"],
  },
  {
    id: "C12-014",
    number: "014",
    title: "Separate Committed Work From Optional Depth",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Derived",
    dependsOn: ["C12-013"],
    summary: "The app must distinguish the action that constitutes today’s commitment from additional work the user may choose.",
    tags: ["daily-ritual", "separate", "violin-stand-partner"],
  },
  {
    id: "C12-015",
    number: "015",
    title: "Reject the Single-Thread Assumption",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Correction",
    dependsOn: ["C12-014"],
    summary: "Allow multiple active practice pages.",
    tags: ["daily-ritual", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-016",
    number: "016",
    title: "Let the User Choose Page Capacity",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Derived",
    dependsOn: ["C12-015"],
    summary: "Users select how many pages they want open.",
    tags: ["daily-ritual", "let", "violin-stand-partner"],
  },
  {
    id: "C12-017",
    number: "017",
    title: "Constrain Every Page to One Current Action",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Derived",
    dependsOn: ["C12-016"],
    summary: "Each open page may contain extensive history but only one current action per day.",
    tags: ["daily-ritual", "constrain", "violin-stand-partner"],
  },
  {
    id: "C12-018",
    number: "018",
    title: "Reject Continuous Daily Reshuffling",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Correction",
    dependsOn: ["C12-017"],
    summary: "Do not regenerate the day’s plan continuously.",
    tags: ["daily-ritual", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-019",
    number: "019",
    title: "Make Today the Primary Operating Surface",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "daily-ritual",
    position: "Derived",
    dependsOn: ["C12-018"],
    summary: "Today is the center of the product.",
    tags: ["daily-ritual", "make", "violin-stand-partner"],
  },
  {
    id: "C12-020",
    number: "020",
    title: "Demote Coach From Product to Orchestration Layer",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "coach-authority",
    position: "Derived",
    dependsOn: [],
    summary: "Coach is powerful but should not become the whole product.",
    tags: ["coach-authority", "demote", "violin-stand-partner"],
  },
  {
    id: "C12-021",
    number: "021",
    title: "Prefer Precise Reflection Over Praise",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "coach-authority",
    position: "Derived",
    dependsOn: ["C12-020"],
    summary: "Avoid generic encouragement.",
    tags: ["coach-authority", "prefer", "violin-stand-partner"],
  },
  {
    id: "C12-022",
    number: "022",
    title: "Make the AI Visibly Corrigible",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "coach-authority",
    position: "Derived",
    dependsOn: ["C12-021"],
    summary: "The AI should be correctable without defensiveness.",
    tags: ["coach-authority", "make", "violin-stand-partner"],
  },
  {
    id: "C12-023",
    number: "023",
    title: "Separate Ben’s Authority From Coach Synthesis",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "coach-authority",
    position: "Derived",
    dependsOn: ["C12-022"],
    summary: "Verified Ben content must remain distinguishable from AI-generated explanation.",
    tags: ["coach-authority", "separate", "violin-stand-partner"],
  },
  {
    id: "C12-024",
    number: "024",
    title: "Prohibit Invented Ben Attribution Under Creative Pressure",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "coach-authority",
    position: "Correction",
    dependsOn: ["C12-023"],
    summary: "The system may not invent Ben-specific stories, memories, quotes, motives, or positions even when explicitly asked to be creative.",
    tags: ["coach-authority", "prohibit", "violin-stand-partner"],
  },
  {
    id: "C12-025",
    number: "025",
    title: "Apply Human First, AI Second",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "method-runtime",
    position: "Foundational",
    dependsOn: [],
    summary: "The AI can execute cognitive and organizational work but cannot take final judgment from the user or appropriate human authority.",
    tags: ["method-runtime", "apply", "violin-stand-partner"],
  },
  {
    id: "C12-026",
    number: "026",
    title: "Translate the Five-Step Method Into Natural Violin Behavior",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "method-runtime",
    position: "Cross-cutting",
    dependsOn: ["C12-025"],
    summary: "The app is governed by: Capture; Why; Why-Not; Commit; Timestamp.",
    tags: ["method-runtime", "translate", "violin-stand-partner"],
  },
  {
    id: "C12-027",
    number: "027",
    title: "Separate Observation From Interpretation",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "method-runtime",
    position: "Cross-cutting",
    dependsOn: ["C12-026"],
    summary: "The system must ask what happened before concluding what it means.",
    tags: ["method-runtime", "separate", "violin-stand-partner"],
  },
  {
    id: "C12-028",
    number: "028",
    title: "Prefer Reversible One-Variable Experiments",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "method-runtime",
    position: "Cross-cutting",
    dependsOn: ["C12-027"],
    summary: "When experimentation is appropriate, change one variable and preserve a path back.",
    tags: ["method-runtime", "prefer", "violin-stand-partner"],
  },
  {
    id: "C12-029",
    number: "029",
    title: "Preserve the Method Outside the App",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "method-runtime",
    position: "Cross-cutting",
    dependsOn: ["C12-028"],
    summary: "The YY Method should remain usable directly from the website.",
    tags: ["method-runtime", "preserve", "violin-stand-partner"],
  },
  {
    id: "C12-030",
    number: "030",
    title: "Reject “Remember Everything”",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "memory",
    position: "Correction",
    dependsOn: [],
    summary: "The AI should not treat the entire conversation as durable memory.",
    tags: ["memory", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-031",
    number: "031",
    title: "Preserve Page History Visibly",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "memory",
    position: "Cross-cutting",
    dependsOn: ["C12-030"],
    summary: "The user must be able to recover context even when the AI forgets.",
    tags: ["memory", "preserve", "violin-stand-partner"],
  },
  {
    id: "C12-032",
    number: "032",
    title: "Require Human Authority Over Durable Memory",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "memory",
    position: "Cross-cutting",
    dependsOn: ["C12-031"],
    summary: "Material memory writes should be visible and correctable.",
    tags: ["memory", "require", "violin-stand-partner"],
  },
  {
    id: "C12-033",
    number: "033",
    title: "Return Memories When They Become Useful",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "memory",
    position: "Cross-cutting",
    dependsOn: ["C12-032"],
    summary: "Memory should be contextual, not constantly visible.",
    tags: ["memory", "return", "violin-stand-partner"],
  },
  {
    id: "C12-034",
    number: "034",
    title: "Reject Unconstrained Conversational Retrieval",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "corpus",
    position: "Correction",
    dependsOn: [],
    summary: "Do not rely on the LLM to search Ben’s entire corpus and generate a confident answer without reviewed structure.",
    tags: ["corpus", "reject", "violin-stand-partner"],
  },
  {
    id: "C12-035",
    number: "035",
    title: "Build a Reviewed Segment-Level Corpus",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "corpus",
    position: "Derived",
    dependsOn: ["C12-034"],
    summary: "Break Ben’s existing videos into addressable teaching segments.",
    tags: ["corpus", "build", "violin-stand-partner"],
  },
  {
    id: "C12-036",
    number: "036",
    title: "Route to the Relevant Source Portion",
    status: "Decided",
    freshness: "Active",
    freshnessNote: "Active. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "corpus",
    position: "Derived",
    dependsOn: ["C12-035"],
    summary: "Send users to the exact relevant segment rather than a full long video.",
    tags: ["corpus", "route", "violin-stand-partner"],
  },
  {
    id: "C12-037",
    number: "037",
    title: "Permit “No Exact Source Found”",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "corpus",
    position: "Derived",
    dependsOn: ["C12-036"],
    summary: "The system must not force a source match.",
    tags: ["corpus", "permit", "violin-stand-partner"],
  },
  {
    id: "C12-038",
    number: "038",
    title: "Narrow the Meaningful Action Surface",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "defensive-judgment",
    position: "Foundational",
    dependsOn: [],
    summary: "The app does not need to solve every problem.",
    tags: ["defensive-judgment", "narrow", "violin-stand-partner"],
  },
  {
    id: "C12-039",
    number: "039",
    title: "Replace Disclaimers With Behavioral Boundaries",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "defensive-judgment",
    position: "Foundational",
    dependsOn: ["C12-038"],
    summary: "Safety disclaimers are insufficient if the model can still generate unrestricted advice.",
    tags: ["defensive-judgment", "replace", "violin-stand-partner"],
  },
  {
    id: "C12-040",
    number: "040",
    title: "Introduce Approved Compacts",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "defensive-judgment",
    position: "Cross-cutting",
    dependsOn: ["C12-039"],
    summary: "Ben’s reviewed lived-experience judgments should be encoded in bounded knowledge units.",
    tags: ["defensive-judgment", "introduce", "violin-stand-partner"],
  },
  {
    id: "C12-041",
    number: "041",
    title: "Put Deterministic Authorization Beneath Probabilistic Intake",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "defensive-judgment",
    position: "Cross-cutting",
    dependsOn: ["C12-040"],
    summary: "The AI may gather context conversationally.",
    tags: ["defensive-judgment", "put", "violin-stand-partner"],
  },
  {
    id: "C12-042",
    number: "042",
    title: "Treat No-Match and Non-Intervention as Successful Outcomes",
    status: "Decided",
    freshness: "Permanent",
    freshnessNote: "Permanent. Revisit if launch evidence, teacher feedback, user behavior, corpus quality, or safety review materially changes this decision.",
    date: "2026-07-17",
    domain: "defensive-judgment",
    position: "Cross-cutting",
    dependsOn: ["C12-041"],
    summary: "The system must not stretch a Compact to fit an uncertain case.",
    tags: ["defensive-judgment", "treat", "violin-stand-partner"],
  }
];

export function getADRCase012(id: string): ADRCase012 | undefined {
  return adrsCase012.find((a) => a.id === id);
}

export function getADRsCase012ByDomain(domain: ADRCase012Domain): ADRCase012[] {
  return adrsCase012.filter((a) => a.domain === domain);
}

export const domainLabelCase012: Record<ADRCase012Domain, string> = {
  "identity": "Product Origin and Identity",
  "audience": "Audience Evolution",
  "daily-ritual": "Daily Ritual and Page Architecture",
  "coach-authority": "Coach and Conversational Authority",
  "method-runtime": "YY Method as Runtime Behavior",
  "memory": "Memory and Longitudinal State",
  "corpus": "Corpus and Knowledge Provenance",
  "defensive-judgment": "Defensive Judgment and First Response",
};
